replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/lora-ticket-classifier
  tag: "c34a756dcb9b418b08b48919d137994835dd1088"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
