replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/lora-ticket-classifier
  tag: "ca065f2c01d198cbdb7064888041518f742ddc54"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
